### ISSUE TITLE
Recursive Blooper

### ISSUE THREAD

**Issue by bmershon** [bmershon/d3-equidecompose#10]
I can't _not_ share this. I fed generated polygons back into the cut algorithm to a depth of 3.

![recursive-blooper](https://cloud.githubusercontent.com/assets/3190945/14406467/5fa1bb32-fe76-11e5-8b42-ea0a9e5b76db.gif)

**Comment by bmershon** [comment]
And a fractal was born.

**Comment by ctralie** [comment]
This is sick!  You can and should include all of this in your final writeup!
