### ISSUE TITLE
Delaunay Triangulation

### ISSUE THREAD

**Issue by bmershon** [bmershon/d3-equidecompose#16]
Use d3-voronoi to triangulate both polygons after rescaling.

**Comment by ctralie** [comment]
Are you sure this works for nonconvex polygons?  I haven't looked at your code closely, but the border of the Delaunay triangulation is the convex hull of the points

**Comment by ctralie** [comment]
(don't worry too much about that...it would be fine if you just had it working for convex polygons.  I just wanted to make you aware of this)

**Comment by bmershon** [comment]
The Delaunay triangulation _would_ create the convex hull if the polygon were not convex when it was fed to `d3.delaunay()`. Delaunay comes for free, which is nice, but we need to figure out another algorithm if we want to support concave shapes.
