### ISSUE TITLE
Triangle to Canonical Rectangle

### ISSUE THREAD

**Issue by bmershon** [bmershon/d3-equidecompose#2]
![triangle-rectangle](https://cloud.githubusercontent.com/assets/3190945/13858265/3b91a538-ec54-11e5-9962-d1cff01b0cff.gif)

Implemented test for triangle to rectangle decomposition in _preflight/_ directory. Test GUI provided.

The _preflight/_ directory is designed to house tests for components (like this one) that are not exposed in the final module. This directory tests a build of _partials.js_ with the exposed `partials` global object.

``` js
...

// partials is an object housing all partial functionality, 
// since d3_equidecompose wouldn't have this method
polygons = partials.triangle2Rectangle([a, b, c]); 
...
```

Note, for example, that the triangle2Rectangle functionality is an internal "private" function that should not be exposed on the d3_equidecompose global object. To test this functionality, we can build a different target with whatever we want to expose, however we want to expose it. This allows the main _test/_ directory to be used for the production module. 

**"Partial" functionality is tested apart from the full-build.**

_This implementation does not do anything fancy to preserve numerical precision._

**Comment by ctralie** [comment]
That GUI is sick

**Comment by bmershon** [comment]
I have not thought too far ahead. This first step eats a triangle and produces an array of polygons. Each polygon is a list of points. We may need to return something other than just a list of polygons produced by a cut.

If we wanted the rectangle represented by the three cuts ([triangle, trapezoid, triangle]), we could recover that with a bounding box calculation. Also, for [hinged dissections](https://en.wikipedia.org/wiki/Hinged_dissection), it may be necessary to return a layout object that notes the pivot vertices and relations between the polygons, rather than just the list of polygons produced.

Therefore, it seems reasonable to start with functions that produce cuts as an array of the resulting polygons.
