### ISSUE TITLE
Animation/Interaction

### ISSUE THREAD

**Issue by bmershon** [bmershon/d3-equidecompose#20]
Running into some bugs with interpolating transforms (translation and rotation about centroid of each polygon).

In the meantime, here's a test to show the correspondences between polygons in a triangle and the generated square.

![highlight](https://cloud.githubusercontent.com/assets/3190945/14896414/9f684252-0d4b-11e6-86ad-c48b49468382.gif)

**Comment by bmershon** [comment]
Rigid translation. Working on rigid rotation.

![rigid-translation](https://cloud.githubusercontent.com/assets/3190945/14923312/81ee90d6-0e0a-11e6-8899-eab4b029891c.gif)

Gif is low framerate, but the actual animation is very smooth.

**Comment by ctralie** [comment]
This is so cool!

**Comment by bmershon** [comment]
And now with staggered rigid translations and rotations.

![rigid-translation-rotation](https://cloud.githubusercontent.com/assets/3190945/14924533/0f961ff2-0e11-11e6-92b3-20894279ecd7.gif)

**Comment by bmershon** [comment]
Again, the actual framerate is fast. Gif is choppy.

![rigid-translation-rotation](https://cloud.githubusercontent.com/assets/3190945/14924562/373fb892-0e11-11e6-87e2-92582fa2fe48.gif)

**Comment by ctralie** [comment]
I love that idea!  This looks fabulous

**Comment by ctralie** [comment]
If you manage to get the whole pipeline I'll send this to Bernard Chazelle straight away

**Comment by bmershon** [comment]
Looking to finish clipping triangle to triangle today. However, we might not get to arbitrary shape to shape decomposition.

**Comment by bmershon** [comment]
And finally, triangle to square looping animation. Staggered translations help the eye track movements.

This exact same pipeline could be used to take a polygon from its position in a target shape (after a clipping algorithm is used) back to its original shape.

Here, if we are cutting shape A (a triangle) into another shape (a square, in this case), then the "original" position is inside the triangle, and the final position of a polygon is wherever it lands in the square.

![fly-animation](https://cloud.githubusercontent.com/assets/3190945/14930780/94853504-0e34-11e6-94ce-1f9084883403.gif)
