### ISSUE TITLE
Issue with right-hand rule in SutherlandHodgeman.

### ISSUE THREAD

**Issue by joypatel100** [bmershon/d3-equidecompose#25]
The sutherlandHodgeman algorithm has a bug.  It is failing to determine whether is point is inside an edge.

**Comment by bmershon** [comment]
Try using d3-polygon `polygonContains`.

```
import {polygonArea, polygonCentroid, polygonContains} from "d3-polygon";
```

**Comment by joypatel100** [comment]
I tried using polygonContains, but I don't think the algorithm works that way. Refer to: https://en.wikipedia.org/wiki/Sutherland%E2%80%93Hodgman_algorithm

**Comment by bmershon** [comment]
Joy implemented clipping. Here's two Delaunay triangulations clipped against one another.

![screen shot 2016-04-30 at 11 25 40 am](https://cloud.githubusercontent.com/assets/3190945/14936917/577e2944-0ec6-11e6-8fce-40f8fe8df5dc.png)

**Comment by bmershon** [comment]
Joy implemented clipping. Here's two Delaunay triangulations clipped against one another.

![screen shot 2016-04-30 at 11 25 40 am](https://cloud.githubusercontent.com/assets/3190945/14936917/577e2944-0ec6-11e6-8fce-40f8fe8df5dc.png)

**Comment by ctralie** [comment]
Great!  Do you think you can push it into the final product, showing at least that you can cut one triangle into another?  This way you don't have to worry about triangulating a polygon.  There will be more special cases to deal with there, but if you get this working, then I can help you finish making it 3D

**Comment by bmershon** [comment]
Our current goal is it incorporate this into #24
