### ISSUE TITLE
Circumcircle triangle of a given area

### ISSUE THREAD

**Issue by bmershon** [bmershon/d3-equidecompose#26]
For the final visualization, I need to pick 2 random points on a circle and then determine the third point on the circle which gives a triangle of a given area.

Ideas welcome.

![circumcircle](https://cloud.githubusercontent.com/assets/3190945/14937315/b11bc9ce-0ed1-11e6-80cb-2a2b3fd28dbf.PNG)

The reason for this is that we can then easily rotate the two common squares into position and smash them together with Joy's clipping algorithm.

See #24

**Comment by bmershon** [comment]
![screen shot 2016-05-01 at 1 39 45 am](https://cloud.githubusercontent.com/assets/3190945/14940273/c5f8d960-0f3d-11e6-8988-ffad88c74f6d.png)

**Comment by bmershon** [comment]
There is numerical instability in the escalator method when vertices are too close together in certain configurations.

We want to sample points so that the inscribed triangle has a given area, and we want to ensure we don't make the triangle too skinny.

**Comment by bmershon** [comment]
I am currently using a _horrible_ numerical approximation hack to iteratively solve for an inscribed triangle with a given area. More on that to come.

For now, there are some numerical precision issues causing two types of problems:
- Errors in the `triangle2Rectangle`  method that propogate to `rectangle2Square`
- Missing pieces following Sutherland-Hodghman clipping

Now is a good time to consider:
- whether Sutherland Hodgman clipping can be rejiggered to work well (treat one of the common squares differently)
- what conditions we need to assume for inputs to the decomposition pipeline

_Working_
![screen shot 2016-05-05 at 8 55 00 pm](https://cloud.githubusercontent.com/assets/3190945/15061581/04e61b54-1305-11e6-8363-431b15c57c2e.png)
_Working_
![screen shot 2016-05-05 at 8 55 51 pm](https://cloud.githubusercontent.com/assets/3190945/15061582/04e6b6e0-1305-11e6-9608-04a64d16b858.png)

_Missing pieces_
![screen shot 2016-05-05 at 8 56 16 pm](https://cloud.githubusercontent.com/assets/3190945/15061583/04e6c702-1305-11e6-9961-b527edbcc510.png)

**Comment by bmershon** [comment]
Creating example, triangle to triangle works!

**Comment by ctralie** [comment]
Congrats Brooks!!
