### ISSUE TITLE
Triangle to Triangle Transform History

### ISSUE THREAD

**Issue by bmershon** [bmershon/d3-equidecompose#27]
We are very close. There is something wrong with the transforms to take a polygon left in the subject triangle all the back to the source triangle. It seems like pieces are undergoing correct translations but stop in an incorrect rotation.

![triangle-triangle-bug](https://cloud.githubusercontent.com/assets/3190945/14943133/01d74ec4-0f9f-11e6-8088-8b2a1fdd9b56.gif)

This and #26 Are the only problems stopping us from having Triangle to Triangle.

**Comment by ctralie** [comment]
This is looking very promising!  Even if all of the transformations aren't correct, is there a way for you to check to see if the pieces look right?  Remember how in my implementation I seemed to get a lot of missing pieces at this stage?

**Comment by bmershon** [comment]
See [README](https://github.com/bmershon/d3-equidecompose#triangle-to-triangle-decomposition) images. The pieces do look right, but every once in a while a pieces that touches the border is missing.

### Internal transformations

First, I view transform histories as an array of operations which, starting at the end of the array (N - 1) and applying in succession until we have applied the first transform, take the polygon in its current position to the source position from which it came. Every time a polygon is moved, the undo operation is pushed onto the array.

I could use a sanity check on the method I use for combining the history of polygons which have come from a source and subject collection and been clipped against one another.
1. Align subject collection (all in a square) with source collection by translating and rotating. Push the undo operations for these two transforms onto the subject polygons' histories.
2. In clipping, concatenate the history of the "subject" polygon with the reversed and "undone" list of transforms stored on the clip polygon. Cache clip polygon's transforms, which include the last two translation and rotation transforms in step 1 to align the common squares.
3. Translate the polygons resulting from the Sutherland-Hodgman clipping by applying the cached clip polygon transforms. _This must be working, because we can see that the animation starts with polygons in the subject triangle._
4. Now The transform history stored on all the final polygons should take the polygon from its current position all the way to the source triangle (subject ---> common square ---> source).

### Tweening

In order to render polygons, I tween two parent SVG transforms under which the polygons are drawn. The **translation** transform simply needs an origin and target translation: the two centroids of the polygon before and after all transforms are applied. The **rotation** transform is nested under the translation transform and simply requires an origin and target rotation _about the centroid_. This rotation is picked up by choosing two candidate vertices by index from a polygon and comparing the angle they make with the centroid of the polygon after all transforms have been applied. This rotation seemed to work in the previous animation (triangle to square), but may very well be the problem now.

### TODO (probably after May 5)

At the end of the day, there are two problems stopping us from having the visualization I would like of inscribed triangle to inscribed triangle tweening:
1. The ability to successfully accumulate transforms and find the rigid translation and rotation needed for the tween. It looks like the rigid translation is correct, but the rotation is wrong.
2. The ability to pick another random inscribed triangle with the same area as a subject triangle. Right now, I cheat and just reverse the vertices of the randomly sampled triangle. This has the affect of generating more pieces for a triangle to (flipped) triangle animation.

**Comment by bmershon** [comment]
This was a bug in the animation.

There are still some tiny numerical precision bugs in Sutherland-Hodgman clipping, but generally triangle-triangle works.

![screen shot 2016-05-05 at 2 52 34 pm](https://cloud.githubusercontent.com/assets/3190945/15053523/0bdd2198-12d1-11e6-81fd-0b4ea4a4ec14.png)
