### ISSUE TITLE
Rewrite without using ES6 syntax

### ISSUE THREAD

**Issue by bmershon** [bmershon/d3-equidecompose#28]
`Let` statements, for example, cannot be parsed by the minifier and seem to be causing problems in Firefox and Safari.

**Comment by ctralie** [comment]
I told you! :)

Too bad though, I appreciate why that's useful

**Comment by bmershon** [comment]
There are a few of the new ECMAScript niceties that I would like to use, and may be able to continue using if I can declare in the script which "newer" version of JavaScript Firefox should use. I don't know about Safari. Chrome supports more than most, it seems, and it didn't occur to me that at least `let` had not been universally accepted as a standard.

The approach Bostock took was to adopt only the module `import` and `export` functionality of the new standard and use tools to allow modular development and a tree-shaking approach to rolling up the files. This is the safe path and the one this code has largely followed. Once the files are built and minified using Rollup --> Uglify-JS, the code behaves like one big script with all of the closures and control over exported global variables that we need. In other words, the production code contains nothing fancy; only the Rollup stage performed offline incorporates technologies that are not supported by the browser. The ability to use modules is a solved problem in Node environments, but not in code made to run in the browser.

I'm using projects like [d3-force](https://github.com/d3/d3-force) as a model for the code layout.

**Comment by bmershon** [comment]
Done. Minified builds work.
