### ISSUE TITLE
The Home Stretch

### ISSUE THREAD

**Issue by bmershon** [bmershon/d3-equidecompose#36]
Two examples of random Delaunay triangulations transformed to form "common squares."

![screen shot 2016-07-06 at 12 03 00 pm](https://cloud.githubusercontent.com/assets/3190945/16629091/b704e30a-4371-11e6-8887-dc8f4e371b13.png)

![screen shot 2016-07-06 at 12 02 00 pm](https://cloud.githubusercontent.com/assets/3190945/16629093/bacb1702-4371-11e6-9568-d598a576d85e.png)

Once a figure has been triangulated, each triangle is transformed into a rectangle with a width determined by the area of the common square implied by the figure.

**Comment by ctralie** [comment]
Looking good!

**Comment by bmershon** [comment]
That was a test to see if you're still subscribed..

On a serious note, I'm trying to decide how to handle incoming meshes or simple polygons when the subject/target figure is not the correct area.

For the Delaunay triangulation example, one might use `d3_equidompose.mesh()` like so:

``` js
<script src="d3-equidecompose.js"></script>

vertices = d3.range(N).map(function(d) {
  return [Math.random() * width / 3, Math.random() * height / 3];
});

source = d3.geom.delaunay(vertices.slice(0, N/3).map(function(d) { return d; });
subject = d3.geom.delaunay(vertices.slice(N/3).map(function(d) { return d; });

var decomposition = d3_equidecompose.mesh(source, subject);

var source = decomposition.source(); // polygons placed in source mesh
var subject = decompositon.subject(); // polygons placed in subject mesh
```

Here, the question is what should `decompositon.subject()` return when the two meshes are not the same area. Should the returned pieces be scaled as necessitated by the algorithm? Or should they be scaled back down to "fit" in the subject shape, where all correspondences are preserved, but pieces shrink or dilate. Easy enough to go either way, an an extra API specification could be added:

```
decomposition.scaled(true);
```

**Comment by bmershon** [comment]
I'm still spotting the occasional missed intersection, but here we have two random Delaunay triangulations for some random points; the subject cloud mesh is scaled so both the source and subject mesh have the same total area.

![screen shot 2016-07-06 at 7 21 58 pm](https://cloud.githubusercontent.com/assets/3190945/16639703/5607881c-43af-11e6-8c97-ef37d2e014a9.png)

As the number of points increases, the time complexity becomes a problem during the clipping stage.

Even more polygons:

![screen shot 2016-07-06 at 7 27 55 pm](https://cloud.githubusercontent.com/assets/3190945/16639762/caaffff0-43af-11e6-97da-1e8d879489e4.png)

**Comment by bmershon** [comment]
This render of just the source decomposition took 2 minutes:

![screen shot 2016-07-06 at 7 28 52 pm](https://cloud.githubusercontent.com/assets/3190945/16639778/f7ba46f4-43af-11e6-8c40-667a7b04d7f9.png)

**Comment by ctralie** [comment]
Great progress!!  Do you have an animation showing the pieces flying into each other?

Also, how long are the computations taking you?

**Comment by bmershon** [comment]
Animation to come. That is something that would be done outside of the module, much the same way I did before. But cleaner. The module just computes static decompositions, either taking in meshes that have already been triangulated, or taking in shapes that will be triangulated internally. Both subject meshes and subject shapes will be scaled if necessary, and some means for accessing the scale and "undoing" the scaling will be provided.

The matter of how to treat the subject falls on the divide between "rendering" and computing. It will probably be convenient to access the scale factor used internally and do with that what you must to scale your resulting decompositions with SVG transforms.

[See](https://github.com/bmershon/d3-equidecompose#api-reference) the in-progress API.

**Right now, clipping is taking way too long and there are numerical instability issues related to teeny tiny polygons.**

I'm assuming that quadratic clipping complexity is going to be a problem, and more checks will be needed to simplify and fudge triangles that get too small. I could use a pointer on those fronts.

EDIT: Oh, also, the high number of pieces is not as aesthetically pleasing as I had hoped it would be. Staggered animation of the pieces tweening into position, however, may look pretty darn cool. Viewing this thing statically, there's too much going on for me to make sense of it when I first look at it.

**Comment by bmershon** [comment]
Basically, if you stick to "low resolution" and triangles that are not too fat and not too skinny, things are ok.

![screen shot 2016-07-06 at 7 42 05 pm](https://cloud.githubusercontent.com/assets/3190945/16640009/e4bcec4e-43b1-11e6-94a2-cc33033c2426.png)

I would like to see if there are different flavors of "triangulators" which might favor _nice_ triangles over a lower number of triangles. As a pre-processing step, this may be a way to get a more pleasing decomposition.

**Comment by ctralie** [comment]
Sorry for the delay in my response!  For the clipping, is the bottleneck that you have to check all of the pieces from polygon A against all of the pieces from polygon B?  If so, I think that can be sped up with logarithmic range searches.  Basically an extension of binary search to the plane.  Or some kind of tiling/hashing

The small pieces is definitely a tougher issue.  Off the top of my head, I wonder if it would help to introduce points into the interior of the polygon to make additional triangles that are better formed.  Something tells me people in the comp geom community have looked into stuff like this, but I don't know.  I'm not sure if that would solve the problem anyway.  At some point it would be great if we could figure out what Shenghan did and if that helps in general

**Comment by bmershon** [comment]
Update:
![equidecomposing-delaunay](https://cloud.githubusercontent.com/assets/3190945/16677464/7b091cf4-4493-11e6-836b-306d2c4f3cb4.gif)

_The jankiness is due to high res and low fps gif, not how the animation looks live in the browser._

The most egregious problem right now, beside the poor clipping time complexity, is the occurrence of null/infinite points and triangles. I need to figure out how to stitch pieces together when intersections occur at infinity, or input triangles have too small of an area.

These are errors were introduced when I rejiggered the way intersections were computed in the clipping process.

**Comment by bmershon** [comment]
While the completion of this module might not be a high research priority, I plan to clean up the code significantly and brand this as a possible learning module, where the goal is for students to examine the source and reverse engineer how it was put together.

EDIT (this is now an update thread...): _Imagine two irregularly shaped stained glass windows in your house. You can point them out to guests and nod while smugly asserting, "yeah, scissor congruent."_

So that's what this will be used for.

**Comment by bmershon** [comment]
Better

![equidecomposing-delaunay](https://cloud.githubusercontent.com/assets/3190945/16677593/cc1b3e50-4494-11e6-8a13-8f10afb1af38.gif)
