### ISSUE TITLE
intersect segment with a (simple, convex) polygon

### ISSUE THREAD

**Issue by bmershon** [bmershon/d3-equidecompose#5]
![cut-polygon](https://cloud.githubusercontent.com/assets/3190945/13895217/2a57222c-ed47-11e5-9bce-1280af29007c.gif)

Still working on some robustness issues.

One crazy idea that came out of attempts trying to cut a polygon near its vertices:
- relax line segment intersection constraints
- clip all polygons cut by a segment to their containing polygon
- pass cuts through a post-processing step that [quantizes vertices](https://github.com/mbostock/topojson-specification/blob/master/README.md#212-transforms) and perhaps does something similar to what [Topojson](https://github.com/mbostock/topojson/wiki) does (infer topology from geographic line data)

**Comment by ctralie** [comment]
I haven't seen that second bug that you sent last night before with convex polygon intersection (did you fix it?  I no longer see it).  I also hope you don't have to quantize the vertices, but if you find that's a necessary step I suppose you can.  Though if you were to do that, I think you could come up with a much easier solution right off the bat which is a kind of flood fill on a pixel grid.  I just don't think this will look as nice though, unless you make the grid very fine.  Have you gotten Joy's input yet?

**Comment by bmershon** [comment]
Joy should have access to this repo and notifications; I'll check with him. These issues are partially to sign post work for myself and others as well as to field suggestions, improvements, fixes.

If you have time on Monday during office hours to do a quick overview of the algorithms with Joy and me, that would be great.

**Comment by ctralie** [comment]
Mos def!
