### ISSUE TITLE
A developing approach to the Tri2Rec cut

### ISSUE THREAD

**Issue by Shenghan-Chen** [bmershon/d3-equidecompose#8]
Here's what I've done in my code: the basic idea is derived from the simplest case of hinged dissection: triangle to rectangle. See this figure below for a most common cut and transformation (which pops up every time you google "hinged dissection").

<img width="602" alt="screen shot 2016-04-07 at 5 50 22 am" src="https://cloud.githubusercontent.com/assets/6370162/14351482/8dd65510-fc9d-11e5-9365-bb9ccda0b5f1.png">
## **A brief clarification of the algorithm**

For a given triangle ABC and a given length w, the purpose is to cut ABC into a rectangle with same area and dimensions w by S/w (where S is the area of ABC). This method should normally give a cut with fewer pieces compared to the technique of "escalator method". Note here w has to be within a certain range that is specified by the shape of the triangle, which will be discussed later. For now just think of w as a "reasonable" edge length. The key point is that w is flexible; in comparison, a canonical rectangle in the original method always has an edge with the same length as one of the triangle's edge.
## **Steps**

**(1)** Find the midpoint E of AC and midpoint F of AB.
**(2)** Find a point X within BC such that EX = w. Note there're generally two such points, and we choose the one that's closer to B. (This can be achieved by find the projection of E onto BC first and then make use of Pythagorean theorem.)
**(3)** Find a point Y within BC such that vector XY = vector BC/2. (The reason of choosing X to be the one closer to B in step 2 is just to ensure that Y is within BC.)
**(4)** Project F and Y onto line segment EX. (Now each piece has a right angle.)

The 4 resulting pieces are capable of a hinged dissection into the desired rectangle. One way of doing it is to fix the upper quadrangle AEMF, choose E, F, X as the anchor points, and rotate the three other pieces 180° around their respective anchor point. This means the purple triangle NXY is hinged to the green quadrangle BXNF at point X, and rotating about X while BXNF is rotating about F. What you get is the rectangle drawn. You can also choose Y as triangle NXY's anchor point and hinge it to quadrangle CEMY. There are other available transformations as well.

It may take some elementary geometry knowledge to see the result is indeed valid. (I can provide a formal proof later if needed.)
## **Relative conditions of w and triangle ABC**

Now the conditions should be addressed, in order for such a construction to exist. There are several of them, and it would take some caution to come up with the complete list:
**(a)** To start with, there's actually a condition for the triangle to meet: angle EBC should be no greater than 90°, otherwise angle FEX must be greater than 90°, and it becomes impossible for F to project onto segment EX (step 4 above).
**(b)** In step 2, apparently w has to be no less than EH, the distance of E to BC, otherwise X can't exist.
**(c)** In step 3, X must be within BD, D being the midpoint of BC, in order for both X and Y to be within BC.
There are two cases to consider:

<img width="553" alt="screen shot 2016-04-07 at 6 05 11 am" src="https://cloud.githubusercontent.com/assets/6370162/14351512/bacf4cac-fc9d-11e5-8c66-2c4724cf95a1.png">
if angle ABC > 90°, then B and D are on different sides of H. Hence, it only requires w (length of EX) ≤ EB, in addition to w ≥ EH in (b).

<img width="561" alt="screen shot 2016-04-07 at 6 05 30 am" src="https://cloud.githubusercontent.com/assets/6370162/14351509/b2e29120-fc9d-11e5-833e-40f00b355005.png">
if angle ABC ≤ 90°, then B and D are on the same side of H, so it requires ED(=FB) ≤ w ≤ EB. Note since ED(=FB) ≥ EH, this condition implies (b).
**(d)** Finally angle EXF should be no greater than 90°. Otherwise the projection of F onto EX would lie beyond segment EX. This condition is even more trickier; see the figure below. If X lies anywhere between x1 and x2, angle EXF would be greater than 90°. On the other hand, x1 and x2 only exist when EH < EF/2. Under such circumstances, it's required that either w ≥ Ex2 or w ≤ Ex1. The exact expressions of Ex1 and Ex2 are kind of tedious, but they should be straightforwardly solvable.
<img width="482" alt="screen shot 2016-04-07 at 8 58 52 am" src="https://cloud.githubusercontent.com/assets/6370162/14351745/fad7355c-fc9e-11e5-8799-d4e959510326.png">
## **How to achieve them**

The methods I used in my code to satisfy or get around with these conditions are the following.

**(i)** First consider conditions (b) and (d). We have to determine a value of w such that w ≥ EH, and if EH < EF/2, then either w ≥ Ex2 or w ≤ Ex1 (we can just let w ≥ Ex2 for convenience). Note the relations should hold for both triangles. From these we obtain a threshold value of w that it should be no less than. Pick such a value of w.

**(ii)** Then consider conditions (c). For a given w, if the current triangle ABC is such that EB < w, then we cut ABC by EB, and rotate the upper triangle ABE 180° about E to form the new triangle A'BC. Then EB in the original triangle essentially becomes F'B in the new one, and E'B becomes longer. Continue such "triangle half cuts" until FB ≤ w ≤ EB is satisfied. On the other hand if FB > w, similarly we cut ABC by FC and rotate triangle ACF 180° about F to form the new triangle ABC, and continue in this manner until condition (c) is met. Note that a "triangle half cut" is a hinged dissection.
<img width="711" alt="screen shot 2016-04-07 at 10 14 21 am" src="https://cloud.githubusercontent.com/assets/6370162/14354143/2be87862-fcaa-11e5-934e-d75b1cfc7363.png">

**(iii)** Finally it's worth mentioning that we can arbitrarily switch points A, B, C to make the triangle ABC ideal. To order to meet condition (a), we can either switch them so that angle ABC isn't the greatest angle among three, or apply the "triangle half cut" discussed above.

Note that w is totally at our choice as long as it's no less than the threshold value obtained in (i). For the current stage of cutting one triangle into another, my hope is to find a value of w such that both triangles can be cut into as few pieces as possible while forming a common rectangle. In other words, I wish to reduce the number of "triangle half cuts" needed. I'm still working on an algorithm to achieve this. Switching points A, B, C should also help; for example, we can make BC to be the shortest edge among three, then it can be shown that the threshold value is actually the lowest, which allows more freedom of choosing w, in order to reduce the total cutting pieces.

Once all conditions are met, carry out the steps above to cut two triangles into a common rectangle. The next step is to overlap the rectangle and do "double cut" using the Sutherland-Hodgman polygon clipping algorithm, as in the python code Chris wrote.
## **A few comments**

Both the "Tri2Rec" and "triangle half cut" transformations are hinged dissections, but unfortunately, hinged dissections are not transitive; that is, if a piece is rotating about different anchor points in two consecutive hinged dissections, then the overall chained transformation isn't a hinged dissection. We can certainly keep them appear as hinged with the presence of intermediate steps, but I'm not sure whether that's something we desire. I also found that 2007 paper titled "hinged dissections exist", but I suppose it would take quite some effort and genius to implement the method introduced.

I'm also thinking about a different way of doing all of these: how about the other way around - cutting a rectangle into two different triangles? It seems to require fewer conditions, and could also save the trouble of using the Sutherland-Hodgman algorithm. I'm currently implementing this, and will write on it later when I'm done.

**P.S.**
I guess this is tediously long to read; nonetheless, what really matters is the steps in doing "Tri2Rec" and the idea of "triangle half cut", since the implementation details are still subject to change. Some mathematical details are omitted as they aren't necessary in implementing the algorithms, and I can fill them in if there's interest and/or need. I'll also learn to add nice gifs of the transformations next time.

**Comment by bmershon** [comment]
Awesome work, Shenghan!

When you get a chance, could you explain your data structure for storing cuts and their transformations?

EDIT: I'm working on digesting this and playing with paper-and-pencil examples.

**Comment by Shenghan-Chen** [comment]
Well, I just used the most straightforward way to store the cuts as a list of vertices. The associated transforms are an object with several fields: anchor point (axis), angle to rotate, a translation and a parent transform, which is the transform of the piece that it's hinged to. So it's essentially a linked list, though I guess an ordinary list would also work.

So the overall applied transformation would be its own rotation/translation first, then its parent's, and all the way up to a root. During the process of animation each angle and translation is scaled by t.

**Comment by bmershon** [comment]
See #17.
